
cloud:
  aws:
    region:
      static: us-east-1
    stack:
      auto: false

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: vendor
  datasource:
    url: jdbc:mysql://localhost:3306/e-com
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      dialect: org.hibernate.dialect.SQLServer2012Dialect
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  http:
    multipart:
      enabled: false

server:
  port: 8083
  compression:
    enabled: true
    min-response-size: 6000
    mime-types: text/html, text/xml, text/plain, text/css, text/javascript, application/javascript, application/json

const:
  security.jwt.secret: '{/<odin>!/3#FuP964>hHdG;QtS!>S}'
  path: 'D:/new Employee task/Authentication/profile-image/'

